#!/bin/bash
# qsub -IP chli -q alloc-dt -l select=1:ncpus=8:mem=45GB,walltime=10:00:00
qsub -IP chli -q alloc-dt -l select=1:ncpus=8:ngpus=1:mpiprocs=8:mem=45GB,walltime=24:00:00
# qsub -IP chli -q alloc-dt -l select=1:ncpus=16:ngpus=2:mpiprocs=16:mem=90GB,walltime=24:00:00
# qsub -IP chli -q alloc-dt -l select=1:ncpus=24:ngpus=3:mpiprocs=24:mem=135GB,walltime=480:00:00
# qsub -IP chli -q alloc-dt -l select=1:ncpus=36:ngpus=4:mpiprocs=32:mem=180GB,walltime=480:00:00
# qsub -IP chli -q alloc-dt -l select=1:ncpus=6:mem=10GB,walltime=480:00:00
