#!/bin/bash
# qsub -IP chli -q alloc-dt -l select=1:ncpus=16:ngpus=2:mpiprocs=16:mem=90GB,walltime=480:00:00
qsub -IP chli -q alloc-dt -l select=1:ncpus=32:ngpus=4:mpiprocs=32:mem=180GB,walltime=480:00:00
