#!/bin/bash

module load cuda/10.0.130 openmpi-gcc/4.0.0-cuda10
# module load python/3.7.2
module load python/3.6.5
module load sqlite
# for ipython
export PATH="/home/chli4934/.local/bin:$PATH"

# # using self installed anaconda rather than module load
# export PATH="/project/chli/anaconda3/bin:$PATH"
# source activate pytorch
# module load glibc/2.14
# source activate ptch

# # pt10 install
# module load binutils/2.30
# module load cuda/9.1.85 openmpi-gcc/3.0.0-cuda
# export CMAKE_PREFIX_PATH="/project/chli/anaconda3/envs/ptch"
# export NCCL_LIB_DIR=/usr/local/cuda/9.1.85/lib64
# export NCCL_INCLUDE_DIR=/usr/local/cuda/9.1.85/include
# conda install numpy pyyaml mkl mkl-include setuptools cmake cffi typing
# conda install -c pytorch magma-cuda91
