#!/bin/bash

module load python/3.5.1
source ~/tf16/bin/activate
module load cuda/9.1.85 openmpi-gcc/3.0.0-cuda

# module load python/3.6.5
# source ~/tf18/bin/activate
# module load cuda/9.0.176 openmpi-gcc/3.0.0-cuda
# module load glibc/2.14
