#!/bin/bash

# Get current window size
X="$(tput cols)"
Y="$(tput lines)"
Y="$(( $Y-1 ))"

# create pytorch sessions
tmux new -s e -n e -x $X -y $Y -d
tmux send -t e:e 'emacs' C-m
tmux new-window -n run -d

# create run sessions
tmux new -s r -n r -x $X -y $Y -d

# create dev sessions
tmux new -s d -n d -x $X -y $Y -d

# create tensorboard/visualize sessions
tmux new -s b -x $X -y $Y -d

