#!/bin/bash

# Get current window size
X="$(tput cols)"
Y="$(tput lines)"
Y="$(( $Y-1 ))"

# create pytorch sessions
tmux new -s e -n e -x $X -y $Y -d
tmux send -t e:e 'emacs' C-m
tmux new-window -n run -d
tmux send -t e:run 'cd ~/current_dev' C-m

# create run sessions
tmux new -s r -n r -x $X -y $Y -d
tmux send -t r:r 'cd ~/current_dev' C-m

# create dev sessions
tmux new -s d -n d -x $X -y $Y -d
tmux new-window -n services -d
tmux send -t d:services 'cd ~/current_dev; pyservesg &' C-m
tmux new-window -n background_processes -d
tmux send -t d:background_processes 'cd /home/ubuntu/richCodeLab/ray_test/rich_rl && docker compose up -d' C-m

# create tensorboard/visualize sessions
tmux new -s b -x $X -y $Y -d

# create system stat sessions
tmux new -s stat -n htop -x $X -y $Y -d
tmux send -t stat:htop 'htop' C-m
