[tool.ruff]
line-length = 65
indent-width = 2
target-version = "py310"
unsafe-fixes = false
preview = false

[tool.ruff.lint]
extend-select = ["I"]
extend-ignore = ["C90", "D210", "E111"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["CPY001"]

[tool.ruff.format]
docstring-code-format = true
# skip-magic-trailing-comma = true
